# pkg.pepit$RESIDUES=""
# pkg.pepit$CONTACT=5.0
# pkg.pepit$PRECISION=1.0
# pkg.pepit$ADD="calpha"
# pkg.pepit$ACC=10
# pkg.pepit$POSE=TRUE
# pkg.pepit$NBCLIQUES=5
# pkg.pepit$NBHITS=20
# pkg.pepit$SCORE=mapping_dist_sum2
# pkg.pepit$MAXDELTADIST=25
# pkg.pepit$MINDIST=0
# pkg.pepit$MINCLIQUE=4
# pkg.pepit$BCMIN=0
# pkg.pepit$INTERCLIQUE=4
# pkg.pepit$NBNEI=4
# pkg.pepit$MAXEDGES=3000000
# pkg.pepit$TYPES=c("a","b","c","o","n","A","C","O","N")
# pkg.pepit$MINSCORE = 10
# pkg.pepit$MAXCLASHES = 10
# pkg.pepit$radius=1.4
# pkg.pepit$PVALUE=FALSE
# pkg.pepit$AAGAP=10
