// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distloc
double distloc(NumericMatrix X, int ind1, int ind2);
RcppExport SEXP _pepit_distloc(SEXP XSEXP, SEXP ind1SEXP, SEXP ind2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type ind1(ind1SEXP);
    Rcpp::traits::input_parameter< int >::type ind2(ind2SEXP);
    rcpp_result_gen = Rcpp::wrap(distloc(X, ind1, ind2));
    return rcpp_result_gen;
END_RCPP
}
// vertex
IntegerMatrix vertex(CharacterVector XProp, CharacterVector YProp);
RcppExport SEXP _pepit_vertex(SEXP XPropSEXP, SEXP YPropSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type XProp(XPropSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type YProp(YPropSEXP);
    rcpp_result_gen = Rcpp::wrap(vertex(XProp, YProp));
    return rcpp_result_gen;
END_RCPP
}
// buildGraph
IntegerMatrix buildGraph(NumericMatrix X, NumericMatrix Y, IntegerMatrix V, double deltadist, double mindist, double maxdist);
RcppExport SEXP _pepit_buildGraph(SEXP XSEXP, SEXP YSEXP, SEXP VSEXP, SEXP deltadistSEXP, SEXP mindistSEXP, SEXP maxdistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type deltadist(deltadistSEXP);
    Rcpp::traits::input_parameter< double >::type mindist(mindistSEXP);
    Rcpp::traits::input_parameter< double >::type maxdist(maxdistSEXP);
    rcpp_result_gen = Rcpp::wrap(buildGraph(X, Y, V, deltadist, mindist, maxdist));
    return rcpp_result_gen;
END_RCPP
}
// mapping_dist_sum2
NumericVector mapping_dist_sum2(NumericMatrix X, IntegerVector I, IntegerVector CI, NumericMatrix Y, IntegerVector J, IntegerVector CJ, double thresh);
RcppExport SEXP _pepit_mapping_dist_sum2(SEXP XSEXP, SEXP ISEXP, SEXP CISEXP, SEXP YSEXP, SEXP JSEXP, SEXP CJSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type I(ISEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type CI(CISEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type J(JSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type CJ(CJSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(mapping_dist_sum2(X, I, CI, Y, J, CJ, thresh));
    return rcpp_result_gen;
END_RCPP
}
// getConnectedNeighbors
IntegerVector getConnectedNeighbors(IntegerVector C, IntegerMatrix V, NumericMatrix X, NumericMatrix Y, double thresh, int nbnei);
RcppExport SEXP _pepit_getConnectedNeighbors(SEXP CSEXP, SEXP VSEXP, SEXP XSEXP, SEXP YSEXP, SEXP threshSEXP, SEXP nbneiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type nbnei(nbneiSEXP);
    rcpp_result_gen = Rcpp::wrap(getConnectedNeighbors(C, V, X, Y, thresh, nbnei));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _pepit_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pepit_distloc", (DL_FUNC) &_pepit_distloc, 3},
    {"_pepit_vertex", (DL_FUNC) &_pepit_vertex, 2},
    {"_pepit_buildGraph", (DL_FUNC) &_pepit_buildGraph, 6},
    {"_pepit_mapping_dist_sum2", (DL_FUNC) &_pepit_mapping_dist_sum2, 7},
    {"_pepit_getConnectedNeighbors", (DL_FUNC) &_pepit_getConnectedNeighbors, 6},
    {"_pepit_rcpp_hello_world", (DL_FUNC) &_pepit_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_pepit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
