# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distloc <- function(X, ind1, ind2) {
    .Call('_pepit_distloc', PACKAGE = 'pepit', X, ind1, ind2)
}

gaploc <- function(ResNo, ind1, ind2) {
    .Call('_pepit_gaploc', PACKAGE = 'pepit', ResNo, ind1, ind2)
}

#' Constructs vertices of correspondence graph
#'
#' @param XProp data frame  N nrows
#' @param YProp data frame  M nrows
#' @param mode 0 atom types comparison, 1 all features' comparison
#' @param size estimated initial size of V
#' @param V output matrix Nvx2 of vertices
#' @description data.frame(eleno, elety, resid, chain, resno, insert, x, y, z, pc, hseu, hsed)
#' @export
vertex <- function(XProp, YProp, mode, size, hse) {
    .Call('_pepit_vertex', PACKAGE = 'pepit', XProp, YProp, mode, size, hse)
}

#' Constructs vertices of correspondence graph
#'
#' @param XProp size N vector of atom types
#' @param YProp size M vector of atom types
#' @param V output matrix Nvx2 of vertices
#' @export
vertex2 <- function(XProp, XHSE, YProp, YHSE) {
    .Call('_pepit_vertex2', PACKAGE = 'pepit', XProp, XHSE, YProp, YHSE)
}

#' Constructs vertices of correspondence graph
#'
#' @param XProp size N vector of atom types 
#' @param XResname size N vector of residue names 
#' @param YProp size M vector of atom types 
#' @param YResname size M vector of residue names 
#' @param V output, matrix Nvx2 of vertices
#' @export
vertex_ho <- function(XProp, XResname, YProp, YResname) {
    .Call('_pepit_vertex_ho', PACKAGE = 'pepit', XProp, XResname, YProp, YResname)
}

#' Constructs vertices of correspondence graph based on residues
#'
#' @param XResno size N vector of residue number
#' @param XResname size N vector of residue names 
#' @param YResno size M vector of residue number
#' @param YResname size M vector of residue names 
#' @param V output, matrix Nvx2 of vertices
#' @export
vertex_ho2 <- function(XResno, XResname, YResno, YResname) {
    .Call('_pepit_vertex_ho2', PACKAGE = 'pepit', XResno, XResname, YResno, YResname)
}

#' Constructs correspondence graph
#'
#' @param X matrix Nx3
#' @param Y matrix Nx3
#' @param V matrix Nvx2
#' @param deltadist double
#' @param mindist double
#' @param maxdist double
#' @export
buildGraph <- function(X, Y, V, deltadist, mindist, maxdist) {
    .Call('_pepit_buildGraph', PACKAGE = 'pepit', X, Y, V, deltadist, mindist, maxdist)
}

#' Constructs correspondence graph
#'
#' @param X matrix Nx3
#' @param Y matrix Nx3
#' @param V matrix Nvx2
#' @param deltadist double
#' @param mindist double
#' @param maxdist double
#' @export
buildGraph_ho <- function(X, XResno, Y, YResno, V, deltadist, mindist, maxdist, maxgap) {
    .Call('_pepit_buildGraph_ho', PACKAGE = 'pepit', X, XResno, Y, YResno, V, deltadist, mindist, maxdist, maxgap)
}

#' Constructs correspondence graph
#'
#' @param X matrix Nx3
#' @param Y matrix Nx3
#' @param V matrix Nvx2
#' @param deltadist double
#' @param mindist double
#' @param maxdist double
#' @export
buildGraph_ho2 <- function(X, XResno, XResInd, Y, YResno, YResInd, V, deltadist, maxgap) {
    .Call('_pepit_buildGraph_ho2', PACKAGE = 'pepit', X, XResno, XResInd, Y, YResno, YResInd, V, deltadist, maxgap)
}

#' @export
mapping_dist_sum2 <- function(X, I, CI, Y, J, CJ, thresh) {
    .Call('_pepit_mapping_dist_sum2', PACKAGE = 'pepit', X, I, CI, Y, J, CJ, thresh)
}

selectLinks <- function(C, V, X, XResno, Y, YResno, thresh, nbnei, maxgap) {
    .Call('_pepit_selectLinks', PACKAGE = 'pepit', C, V, X, XResno, Y, YResno, thresh, nbnei, maxgap)
}

