# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distloc <- function(X, ind1, ind2) {
    .Call('_pepit_distloc', PACKAGE = 'pepit', X, ind1, ind2)
}

#' Constructs vertices of correspondence graph
#'
#' @param XProp vecteur of atom types N
#' @param YProp vecteur of atom types N
#' @param V matrix Nvx2 of vertices
#' @export
vertex <- function(XProp, YProp) {
    .Call('_pepit_vertex', PACKAGE = 'pepit', XProp, YProp)
}

#' Constructs correspondence graph
#'
#' @param X matrix Nx3
#' @param Y matrix Nx3
#' @param V matrix Nvx2
#' @param deltadist double
#' @param mindist double
#' @param maxdist double
#' @export
buildGraph <- function(X, Y, V, deltadist, mindist, maxdist) {
    .Call('_pepit_buildGraph', PACKAGE = 'pepit', X, Y, V, deltadist, mindist, maxdist)
}

#' @export
mapping_dist_sum2 <- function(X, I, CI, Y, J, CJ, thresh) {
    .Call('_pepit_mapping_dist_sum2', PACKAGE = 'pepit', X, I, CI, Y, J, CJ, thresh)
}

getConnectedNeighbors <- function(C, V, X, Y, thresh, nbnei) {
    .Call('_pepit_getConnectedNeighbors', PACKAGE = 'pepit', C, V, X, Y, thresh, nbnei)
}

rcpp_hello_world <- function() {
    .Call('_pepit_rcpp_hello_world', PACKAGE = 'pepit')
}

